
path: '/Users/kmmaulen/Desktop/yolov8/midterm/data' # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/test  # val images (relative to 'path')

# Classes
names:
  0: cat
  1: dog
